/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jm_proy;

/**
 *
 * @author monitorvdo10
 */
public class JFrameMainTwo extends javax.swing.JFrame {
    
    
    private int index;
    //private String namePlayer;
    private Player player;
    private String stringLives = "Vidas :";
    QuestMaker questMaker;

    /**
     * Creates new form JFrameMainTwo
     */
    public JFrameMainTwo(String namePlayer) {
        initComponents();
        //this.namePlayer = namePlayer;
        questMaker = new QuestMaker();
        player = new Player(namePlayer);
        index = 0;
        initQuest();
    }
    
    private void initQuest(){
        
        
        Quest quest = questMaker.doQuest(index);
        int lvlCount = index+1;
        txtLvl.setText("Nivel: "+lvlCount);
        
        //preguntas
        txtQuest.setText(quest.getQuestion());
        
        //respuestas
        printAnswers(quest);
        /*
        txtAnsA.setText(quest.getAnsCorrect());
        txtAnsB.setText(quest.getAnsNoCorrect1());
        txtAnsC.setText(quest.getAnsNoCorrect2());
        txtAnsD.setText(quest.getAnsNoCorrect3());
        */
        
        //info player
            //nombre
        txtNamePlayer.setText(player.getName());
            //vidas
        txtLives.setText(stringLives+ player.getLives());
        
    }
    
    private void doAnswer(javax.swing.JLabel txtLabel, int i, String ans){
        QuestMaker questMaker = new QuestMaker();
        boolean boolAns = questMaker.isCorrect(i, txtLabel.getText());
        if(boolAns){
            System.out.println("Correcto");
            System.out.println("Siguiente pregunta");
            if(i!=9){
                this.nextQuest();
            }else{
                ultimateQuestion();
            }
            
        }else{
            System.out.println("Incorrecto");
            player.reduceLives();
            if(player.gameOver()){
                gameOverWindow();
            }
            txtLives.setText(stringLives+player.getLives());
        }
    }
    
    private void nextQuest(){
        index++;
        //this.initComponents();
        this.initQuest();
        //this.updateUI();
    }
    
    private void ultimateQuestion(){
        System.out.println("Ganó compa!");
        JFGameWon jFGameWon = new JFGameWon(player.getName());
        jFGameWon.setVisible(true);
        this.dispose();
    }
    
    private void gameOverWindow(){
        JFrameGameOverTwo jFrameGameOverTwo = new JFrameGameOverTwo();
        jFrameGameOverTwo.setVisible(true);
        this.dispose();
    }
    
    private void printAnswers(Quest quest){
         int valorDado = (int) Math.floor(Math.random()*4);
         System.out.println("valor random: "+valorDado);
         //Quest quest = questMaker.doQuest(index);
         
         String[] answers = {
             quest.getAnsCorrect(),
             quest.getAnsNoCorrect1(),
             quest.getAnsNoCorrect2(),
             quest.getAnsNoCorrect3()
         };
         
         txtAnsA.setText(answers[valorDado]);
         
         //modifico valor dado
         valorDado = (valorDado+1)%4; //toma un valor entre 0
         txtAnsB.setText(answers[valorDado]);
         
         //modifico valor 2da vez
         valorDado = (valorDado+1)%4; //toma un valor entre 0
         txtAnsC.setText(answers[valorDado]);
         
         //modifico valor 3ra vez
         valorDado = (valorDado+1)%4; //toma un valor entre 0
         txtAnsD.setText(answers[valorDado]);
         
         String txtSelected = "txtAns"+"A";
         
         /*
         int i = 3;
         do{
             String txtSelectd = "txtAns"+valorDado;
             System.out.println("Txt Selected: "+txtSelectd);
             i--;
         }while(i>0);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtQuest = new javax.swing.JLabel();
        txtLvl = new javax.swing.JLabel();
        txtLives = new javax.swing.JLabel();
        txtNamePlayer = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtAnsB = new javax.swing.JLabel();
        txtAnsD = new javax.swing.JLabel();
        txtAnsA = new javax.swing.JLabel();
        txtAnsC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtQuest.setBackground(new java.awt.Color(51, 51, 255));
        txtQuest.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        txtQuest.setForeground(new java.awt.Color(51, 153, 0));
        txtQuest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQuest.setText("X1 op X2");
        txtQuest.setBorder(javax.swing.BorderFactory.createTitledBorder("Pregunta"));

        txtLvl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLvl.setText("Nivel Aquí");
        txtLvl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtLives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLives.setText("Lives aquí");
        txtLives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNamePlayer.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        txtNamePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNamePlayer.setText("name Aquí");
        txtNamePlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtQuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLives, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNamePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtLives)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAnsB.setBackground(new java.awt.Color(51, 51, 255));
        txtAnsB.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        txtAnsB.setForeground(new java.awt.Color(51, 153, 0));
        txtAnsB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnsB.setText("B");
        txtAnsB.setBorder(javax.swing.BorderFactory.createTitledBorder("B"));
        txtAnsB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnsBMouseClicked(evt);
            }
        });

        txtAnsD.setBackground(new java.awt.Color(51, 51, 255));
        txtAnsD.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        txtAnsD.setForeground(new java.awt.Color(51, 153, 0));
        txtAnsD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnsD.setText("D");
        txtAnsD.setBorder(javax.swing.BorderFactory.createTitledBorder("D"));
        txtAnsD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnsDMouseClicked(evt);
            }
        });

        txtAnsA.setBackground(new java.awt.Color(51, 51, 255));
        txtAnsA.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        txtAnsA.setForeground(new java.awt.Color(51, 153, 0));
        txtAnsA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnsA.setText("A");
        txtAnsA.setBorder(javax.swing.BorderFactory.createTitledBorder("A"));
        txtAnsA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAnsAFocusGained(evt);
            }
        });
        txtAnsA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnsAMouseClicked(evt);
            }
        });

        txtAnsC.setBackground(new java.awt.Color(51, 51, 255));
        txtAnsC.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        txtAnsC.setForeground(new java.awt.Color(51, 153, 0));
        txtAnsC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAnsC.setText("C");
        txtAnsC.setBorder(javax.swing.BorderFactory.createTitledBorder("C"));
        txtAnsC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnsCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtAnsA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(txtAnsB, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtAnsC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAnsD, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnsB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnsA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnsD, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnsC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnsBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnsBMouseClicked
        // TODO add your handling code here:
        //selectTxtAns();
        this.doAnswer(txtAnsB, index, txtAnsB.getText());
    }//GEN-LAST:event_txtAnsBMouseClicked

    private void txtAnsDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnsDMouseClicked
        // TODO add your handling code here:
        this.doAnswer(txtAnsD, index, txtAnsD.getText());
    }//GEN-LAST:event_txtAnsDMouseClicked

    private void txtAnsAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAnsAFocusGained
        // TODO add your handling code here:
        //txtAnsA.setBackground(Color.red);
    }//GEN-LAST:event_txtAnsAFocusGained

    private void txtAnsAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnsAMouseClicked
        // TODO add your handling code here:
        this.doAnswer(txtAnsA, index, txtAnsA.getText());
    }//GEN-LAST:event_txtAnsAMouseClicked

    private void txtAnsCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnsCMouseClicked
        // TODO add your handling code here:
        this.doAnswer(txtAnsC, index, txtAnsC.getText());
    }//GEN-LAST:event_txtAnsCMouseClicked

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMainTwo().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txtAnsA;
    private javax.swing.JLabel txtAnsB;
    private javax.swing.JLabel txtAnsC;
    private javax.swing.JLabel txtAnsD;
    private javax.swing.JLabel txtLives;
    private javax.swing.JLabel txtLvl;
    private javax.swing.JLabel txtNamePlayer;
    private javax.swing.JLabel txtQuest;
    // End of variables declaration//GEN-END:variables

    
}
